name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache vcpkg dependencies
        uses: actions/cache@v4
        with:
          # The path to cache is the entire vcpkg directory
          path: ${{ github.workspace }}/vcpkg
          # The key is specific to the OS and the contents of your vcpkg manifest
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          # A fallback key to restore the latest cache for the current OS
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libvulkan-dev \
            libxinerama-dev \
            libxcursor-dev \
            xorg-dev \
            libglu1-mesa-dev \
            pkg-config \
            clang-tidy

      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake with compile commands
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release
